{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authforge.fullname" . }}-secrets
  labels:
    {{- include "authforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "authforge.backendSecretData" . | nindent 2 }}
{{- end }}
