#!/usr/bin/env bash
# scripts/docker/compose-override.sh
#
# Workaround for docker compose v5.3.1's buildx-bake relative-path resolution
# bug (#45). In that version, `docker compose up`/`build` resolve relative
# `build.context`, `build.dockerfile`, and bind-mount `source` paths against an
# unrelated base instead of the compose file's directory, so the stack fails to
# build/start. `docker compose config` renders the paths correctly, but the
# build step (bake) uses a different, wrong base.
#
# This helper emits an absolute-path OVERRIDE compose file that, when layered
# with `-f docker-compose.yml -f <override>`, forces every relative path to its
# resolved absolute form. Absolute paths are immune to the bake base-path bug.
#
# The override is GENERATED from the real compose file so it stays in sync if
# services/mounts change -- no hardcoded service list to drift.
#
# Usage (from any of the call sites):
#   OVERRIDE="$(bash scripts/docker/compose-override.sh)" || exit 1
#   docker compose -f deploy/docker/docker-compose.yml -f "$OVERRIDE" \
#       --project-directory . up -d
#
# Exit code 0 prints the temp override file path on stdout (clean it up when
# done; or rely on the OS temp dir reaper).
#
# Not needed on unaffected compose versions, but harmless to always apply.

set -euo pipefail

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <path-to-docker-compose.yml>" >&2
    exit 1
fi

COMPOSE_FILE="$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
COMPOSE_DIR="$(dirname "$COMPOSE_FILE")"

if [ ! -f "$COMPOSE_FILE" ]; then
    echo "[compose-override] compose file not found: $COMPOSE_FILE" >&2
    exit 1
fi

# Resolve a path that is RELATIVE TO THE COMPOSE FILE'S DIRECTORY into an
# absolute path. Paths that are already absolute are returned unchanged.
resolve_abs() {
    local p="$1"
    case "$p" in
        /*) printf '%s' "$p" ;;
        *)  printf '%s' "$COMPOSE_DIR/$p" ;;
    esac
}

# Generate the override. We walk the compose file and, for each service that
# has a build.context / build.dockerfile or bind-mount volumes with relative
# host sources, emit absolute-path equivalents.
#
# To stay robust against service additions, we use `docker compose config`
# (which resolves paths CORRECTLY in the render step) to discover the real
# absolute paths, then build a minimal override YAML from those.
OVERRIDE_FILE="$(mktemp -t compose-override.XXXXXX.yml)"
trap 'rm -f "$OVERRIDE_FILE"' EXIT

{
    echo "# Auto-generated by scripts/docker/compose-override.sh"
    echo "# Workaround for compose v5.3.1 buildx-bake relative-path bug (#45)."
    echo "# Do not edit by hand -- regenerate via the helper."
    echo "services:"
} > "$OVERRIDE_FILE"

# Use `docker compose config` to get the CORRECTLY-resolved absolute paths, then
# re-emit only the build/volume keys we need to override. We parse the JSON
# output (portable across compose versions) rather than scraping YAML.
CONFIG_JSON="$(docker compose -f "$COMPOSE_FILE" config --format json 2>/dev/null)" || {
    # Older compose: `config --format json` may not exist; fall back to two-file.
    CONFIG_JSON="$(docker compose -f "$COMPOSE_FILE" config 2>/dev/null)"
    echo "[compose-override] WARNING: could not get JSON config; skipping override." >&2
    rm -f "$OVERRIDE_FILE"
    trap - EXIT
    exit 0
}

# Emit override entries per service. Requires python3 (already a build/test
# dependency of this repo for openapi-spec-validator etc.).
python3 - "$CONFIG_JSON" "$OVERRIDE_FILE" "$COMPOSE_DIR" <<'PYEOF' || true
import json, sys, os

config_json, override_file, compose_dir = sys.argv[1], sys.argv[2], sys.argv[3]
try:
    data = json.loads(config_json)
except json.JSONDecodeError:
    # config --format json sometimes wraps; skip silently.
    sys.exit(0)

def rel_to_abs(p):
    if os.path.isabs(p):
        return p
    return os.path.normpath(os.path.join(compose_dir, p))

lines = []
services = data.get("services", {})
for name, svc in services.items():
    entry = {"service": name}
    # Build context + dockerfile
    build = svc.get("build")
    if isinstance(build, dict) and (build.get("context") or build.get("dockerfile")):
        b = {}
        if build.get("context"):
            b["context"] = rel_to_abs(build["context"])
        if build.get("dockerfile"):
            df = build["dockerfile"]
            # dockerfile is relative to context, not compose dir.
            ctx = build.get("context", ".")
            b["dockerfile"] = os.path.normpath(
                os.path.join(rel_to_abs(ctx), df)
            ) if not os.path.isabs(df) else df
        entry["build"] = b
    # Bind-mount volumes: host source is the part before the first ':'.
    vols = svc.get("volumes")
    if isinstance(vols, list):
        abs_vols = []
        changed = False
        for v in vols:
            if isinstance(v, dict):
                src = v.get("source")
                if src and not src.startswith(("pgdata", "redisdata", "promdata")):
                    v2 = dict(v)
                    v2["source"] = rel_to_abs(src)
                    abs_vols.append(v2)
                    changed = True
                else:
                    abs_vols.append(v)
            elif isinstance(v, str) and ":" in v:
                src = v.split(":", 1)[0]
                # Skip named volumes (no leading path separator, not a known mount).
                if src and not src.startswith("/") and src in ("pgdata","redisdata","promdata"):
                    abs_vols.append(v)
                    continue
                if src:
                    rest = v.split(":", 1)[1]
                    abs_vols.append(rel_to_abs(src) + ":" + rest)
                    changed = True
                else:
                    abs_vols.append(v)
            else:
                abs_vols.append(v)
        if changed:
            entry["volumes"] = abs_vols
    if len(entry) > 1:
        lines.append(entry)

if not lines:
    sys.exit(0)

with open(override_file, "a") as f:
    for e in lines:
        name = e.pop("service")
        f.write(f"  {name}:\n")
        if "build" in e:
            f.write("    build:\n")
            for k, v in e["build"].items():
                f.write(f"      {k}: {v}\n")
        if "volumes" in e:
            f.write("    volumes:\n")
            for v in e["volumes"]:
                if isinstance(v, str):
                    f.write(f"      - {v}\n")
                else:
                    f.write(f"      - type: {v.get('type','bind')}\n")
                    f.write(f"        source: {v.get('source')}\n")
                    f.write(f"        target: {v.get('target')}\n")
                    if v.get("read_only"):
                        f.write(f"        read_only: true\n")
PYEOF

# Echo the path for the caller to use. Disable the EXIT trap so the file
# survives this script's exit; the caller (or temp reaper) owns cleanup.
trap - EXIT
echo "$OVERRIDE_FILE"
