{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fulla.fullname" . }}-secrets
  labels:
    {{- include "fulla.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "fulla.backendSecretData" . | nindent 2 }}
{{- end }}
