// Sidebar mirrors the site IA; docs/ is user-facing only (governance §4A).
// Category labels are English (site default locale); doc item labels derive
// from each file's own H1, so the zh-CN tree shows Chinese titles
// automatically. Maintainer archives (history, branding, process docs) live
// in docs-local/ outside this tree and are NOT site content.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Evaluate',
      items: [
        'architecture/architecture-overview',
        'architecture/security-architecture',
        {
          type: 'link',
          label: 'Benchmark Report',
          href: 'https://github.com/voidvec/fulla/blob/master/benchmarks/competitors/results/COMPARISON.md',
        },
        'benchmark/competitor-benchmark-design',
      ],
    },
    {
      type: 'category',
      label: 'Integrate',
      items: [
        'sdk/sdk-integration-guide',
        'sdk/sdk-runtime-contract',
        'domains/api-reference',
        'domains/oidc-guide',
        'domains/social-login',
        'domains/rbac-guide',
      ],
    },
    {
      type: 'category',
      label: 'Deep Dives',
      items: [
        'domains/token-lifecycle',
        'domains/session-management',
        'domains/multi-tenancy',
        'architecture/data-persistence',
      ],
    },
    {
      type: 'category',
      label: 'Operate',
      items: [
        'operate/deployment',
        'operate/docker-deployment',
        'operate/deployment-windows-docker-desktop',
        'operate/configuration-guide',
        'operate/observability',
        'operate/account-lockout',
        'operate/postgresql-major-upgrade',
        'operate/verification-checklist',
      ],
    },
    {
      type: 'category',
      label: 'Contribute',
      items: [
        'contribute/testing-guide',
        'contribute/ci-cd-guide',
        'contribute/versioning-and-release',
        'documentation-governance',
        'contribute/admin-test-cases',
        'contribute/user-frontend-test-cases',
        'contribute/admin-e2e-testing-guide',
      ],
    },
    { type: 'autogenerated', dirName: 'adr' },
  ],
};

module.exports = sidebars;
