// Sidebar mirrors the site IA; docs/ is user-facing only (governance §2):
// architecture / domains / sdk / operate / contribute zones + ADRs.
// Maintainer archives (history, branding records, process docs) live in
// docs-local/ outside this tree and are NOT site content.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: '评估 · Evaluate',
      items: [
        'architecture/architecture-overview',
        'architecture/security-architecture',
        {
          type: 'link',
          label: '性能对比报告',
          href: 'https://github.com/voidvec/fulla/blob/master/benchmarks/competitors/results/COMPARISON.md',
        },
        'benchmark/competitor-benchmark-design',
      ],
    },
    {
      type: 'category',
      label: '集成 · Integrate',
      items: [
        'sdk/sdk-integration-guide',
        'sdk/sdk-runtime-contract',
        'domains/api-reference',
        'domains/oidc-guide',
        'domains/social-login',
        'domains/rbac-guide',
      ],
    },
    {
      type: 'category',
      label: '架构深潜 · Architecture',
      items: ['architecture/data-persistence'],
    },
    {
      type: 'category',
      label: '运维 · Operate',
      items: [
        'operate/deployment',
        'operate/docker-deployment',
        'operate/deployment-windows-docker-desktop',
        'operate/configuration-guide',
        'operate/observability',
        'operate/account-lockout',
        'operate/postgresql-major-upgrade',
        'operate/verification-checklist',
      ],
    },
    {
      type: 'category',
      label: '贡献 · Contribute',
      items: [
        'contribute/testing-guide',
        'contribute/ci-cd-guide',
        'contribute/versioning-and-release',
        'documentation-governance',
        'contribute/admin-test-cases',
        'contribute/user-frontend-test-cases',
        'contribute/admin-e2e-testing-guide',
      ],
    },
    { type: 'autogenerated', dirName: 'adr' },
  ],
};

module.exports = sidebars;
