// Five-zone sidebar mirroring docs/README.md's audience navigation.
// Doc ids default to filename-without-extension; see frontend/test-cases.md
// frontmatter for the one collision fix (admin/test-cases.md shares the name).

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: '评估 · Evaluate',
      items: [
        'backend/architecture-overview',
        'backend/security-architecture',
        {
          type: 'link',
          label: '性能对比报告',
          href: 'https://github.com/voidvec/fulla/blob/master/benchmarks/competitors/results/COMPARISON.md',
        },
        'benchmark/competitor-benchmark-design',
      ],
    },
    {
      type: 'category',
      label: '集成 · Integrate',
      items: [
        'backend/sdk-integration-guide',
        'backend/sdk-runtime-contract',
        'backend/api-reference',
        'backend/oidc-guide',
        'backend/social-login',
        'backend/rbac-guide',
      ],
    },
    {
      type: 'category',
      label: '运维 · Operate',
      items: [
        'ops/deployment',
        'backend/docker-deployment',
        'ops/deployment-windows-docker-desktop',
        'backend/configuration-guide',
        'backend/observability',
        'ops/account-lockout',
        'ops/postgresql-major-upgrade',
        'ops/verification-checklist',
      ],
    },
    {
      type: 'category',
      label: '贡献 · Contribute',
      items: [
        'backend/testing-guide',
        'backend/ci-cd-guide',
        'backend/versioning-and-release',
        'documentation-governance',
        'admin/test-cases',
        'frontend/test-cases',
        'admin/e2e-testing-guide',
      ],
    },
    {
      type: 'category',
      label: '档案 · Archive',
      items: [
        { type: 'autogenerated', dirName: 'adr' },
        { type: 'autogenerated', dirName: 'history' },
        'backend/ddd-domain-model',
        'branding/rename-impact-fulla',
        'branding/repo-professionalization-audit',
        'productization-evolution/done/oauth-oidc-compliance-audit',
      ],
    },
  ],
};

module.exports = sidebars;
